import React from 'react';
import Chart from 'react-apexcharts';

const LineChart = () => {
  const data = [
    {
      "srcStateName": "Telangana",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 22.3,
      "Heart Disease": 3.3,
      "Stroke": 2.2,
      "Diabetes Mellitus": 13.1,
      "Neurological/Psychiatric Conditions": 3.2,
      "Cancer": 3.3,
      "Number of older adults": 2449,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Tamil Nadu",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 23.3,
      "Heart Disease": 4.4,
      "Stroke": 3.7,
      "Diabetes Mellitus": 22.4,
      "Neurological/Psychiatric Conditions": 4.4,
      "Cancer": 3.3,
      "Number of older adults": 3520,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Puducherry",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 30.3,
      "Heart Disease": 8.4,
      "Stroke": 1.8,
      "Diabetes Mellitus": 26.9,
      "Neurological/Psychiatric Conditions": 3.2,
      "Cancer": 3.1,
      "Number of older adults": 1422,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Lakshadweep",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 42.7,
      "Heart Disease": 7.3,
      "Stroke": 4.6,
      "Diabetes Mellitus": 34.2,
      "Neurological/Psychiatric Conditions": 2,
      "Cancer": 3.4,
      "Number of older adults": 1130,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Kerala",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 54.5,
      "Heart Disease": 20.5,
      "Stroke": 7.8,
      "Diabetes Mellitus": 51.9,
      "Neurological/Psychiatric Conditions": 7.9,
      "Cancer": 15,
      "Number of older adults": 2460,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Karnataka",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 31.4,
      "Heart Disease": 11.9,
      "Stroke": 9.2,
      "Diabetes Mellitus": 25.1,
      "Neurological/Psychiatric Conditions": 7.6,
      "Cancer": 8.8,
      "Number of older adults": 2375,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Andhra Pradesh",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 23,
      "Heart Disease": 4.5,
      "Stroke": 3.4,
      "Diabetes Mellitus": 16.6,
      "Neurological/Psychiatric Conditions": 3.2,
      "Cancer": 2.4,
      "Number of older adults": 2656,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Andaman & Nicobar Islands",
      "Region": "South",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 22.2,
      "Heart Disease": 3.3,
      "Stroke": 2.5,
      "Diabetes Mellitus": 15.2,
      "Neurological/Psychiatric Conditions": 3,
      "Cancer": 2.4,
      "Number of older adults": 1240,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Maharashtra",
      "Region": "West",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 24.9,
      "Heart Disease": 10,
      "Stroke": 8.3,
      "Diabetes Mellitus": 16.3,
      "Neurological/Psychiatric Conditions": 4.1,
      "Cancer": 5.4,
      "Number of older adults": 3952,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Gujarat",
      "Region": "West",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 8.6,
      "Heart Disease": 10.1,
      "Stroke": 5.8,
      "Diabetes Mellitus": 14.4,
      "Neurological/Psychiatric Conditions": 5.7,
      "Cancer": 7.6,
      "Number of older adults": 2308,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Goa",
      "Region": "West",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 37.5,
      "Heart Disease": 14,
      "Stroke": 8,
      "Diabetes Mellitus": 27.8,
      "Neurological/Psychiatric Conditions": 7.1,
      "Cancer": 3.8,
      "Number of older adults": 1418,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Daman & Diu",
      "Region": "West",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 11.4,
      "Heart Disease": 7.6,
      "Stroke": 3,
      "Diabetes Mellitus": 18.5,
      "Neurological/Psychiatric Conditions": 4.5,
      "Cancer": 6.6,
      "Number of older adults": 981,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Dadra & Nagar Haveli",
      "Region": "West",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 8,
      "Heart Disease": 8.8,
      "Stroke": 3.8,
      "Diabetes Mellitus": 13.2,
      "Neurological/Psychiatric Conditions": 3.1,
      "Cancer": 6.6,
      "Number of older adults": 1073,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Tripura",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 19.9,
      "Heart Disease": 5.2,
      "Stroke": 8.9,
      "Diabetes Mellitus": 10.3,
      "Neurological/Psychiatric Conditions": 2.7,
      "Cancer": 5,
      "Number of older adults": 1177,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Nagaland",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 7.9,
      "Heart Disease": 1,
      "Stroke": 2.5,
      "Diabetes Mellitus": 2.6,
      "Neurological/Psychiatric Conditions": 0.5,
      "Cancer": 1.7,
      "Number of older adults": 1304,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Mizoram",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 27.1,
      "Heart Disease": 7.8,
      "Stroke": 4.2,
      "Diabetes Mellitus": 14.3,
      "Neurological/Psychiatric Conditions": 4.5,
      "Cancer": 19.6,
      "Number of older adults": 1241,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Meghalaya",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 25.1,
      "Heart Disease": 2.4,
      "Stroke": 4.3,
      "Diabetes Mellitus": 10.5,
      "Neurological/Psychiatric Conditions": 1,
      "Cancer": 2.1,
      "Number of older adults": 967,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Manipur",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 27.2,
      "Heart Disease": 8.1,
      "Stroke": 10.5,
      "Diabetes Mellitus": 14.7,
      "Neurological/Psychiatric Conditions": 4.8,
      "Cancer": 8.4,
      "Number of older adults": 1362,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Assam",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 41.7,
      "Heart Disease": 5.8,
      "Stroke": 4.7,
      "Diabetes Mellitus": 12.6,
      "Neurological/Psychiatric Conditions": 5,
      "Cancer": 6,
      "Number of older adults": 2333,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Arunachal Pradesh",
      "Region": "Northeast",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 21.9,
      "Heart Disease": 3.7,
      "Stroke": 1.9,
      "Diabetes Mellitus": 9.3,
      "Neurological/Psychiatric Conditions": 1,
      "Cancer": 0.9,
      "Number of older adults": 1212,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "West Bengal",
      "Region": "East",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 33.2,
      "Heart Disease": 17.2,
      "Stroke": 17.4,
      "Diabetes Mellitus": 19,
      "Neurological/Psychiatric Conditions": 7.7,
      "Cancer": 7.1,
      "Number of older adults": 3897,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Odisha",
      "Region": "East",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 16.2,
      "Heart Disease": 3.1,
      "Stroke": 2.6,
      "Diabetes Mellitus": 9.5,
      "Neurological/Psychiatric Conditions": 4.1,
      "Cancer": 3.5,
      "Number of older adults": 2898,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Jharkhand",
      "Region": "East",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 11.5,
      "Heart Disease": 2.5,
      "Stroke": 0.8,
      "Diabetes Mellitus": 7.5,
      "Neurological/Psychiatric Conditions": 4.5,
      "Cancer": 2.2,
      "Number of older adults": 2450,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Bihar",
      "Region": "East",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 23.9,
      "Heart Disease": 8.3,
      "Stroke": 2.9,
      "Diabetes Mellitus": 13.6,
      "Neurological/Psychiatric Conditions": 10.1,
      "Cancer": 4,
      "Number of older adults": 3512,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Uttar Pradesh",
      "Region": "Central",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 11.8,
      "Heart Disease": 5,
      "Stroke": 4.6,
      "Diabetes Mellitus": 9.1,
      "Neurological/Psychiatric Conditions": 5,
      "Cancer": 4.1,
      "Number of older adults": 4520,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Madhya Pradesh",
      "Region": "Central",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 13,
      "Heart Disease": 5.9,
      "Stroke": 3.7,
      "Diabetes Mellitus": 9.3,
      "Neurological/Psychiatric Conditions": 5.8,
      "Cancer": 3.5,
      "Number of older adults": 2907,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Chhattisgarh",
      "Region": "Central",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 10,
      "Heart Disease": 2.1,
      "Stroke": 4.5,
      "Diabetes Mellitus": 6.5,
      "Neurological/Psychiatric Conditions": 2.8,
      "Cancer": 2.4,
      "Number of older adults": 2052,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Uttarakhand",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 15.2,
      "Heart Disease": 7.4,
      "Stroke": 2.2,
      "Diabetes Mellitus": 10.5,
      "Neurological/Psychiatric Conditions": 3.9,
      "Cancer": 5.4,
      "Number of older adults": 1354,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Rajasthan",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 16.3,
      "Heart Disease": 4.9,
      "Stroke": 2.4,
      "Diabetes Mellitus": 9.8,
      "Neurological/Psychiatric Conditions": 3.9,
      "Cancer": 3.8,
      "Number of older adults": 2233,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Punjab",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 25.8,
      "Heart Disease": 10.6,
      "Stroke": 5.6,
      "Diabetes Mellitus": 17.9,
      "Neurological/Psychiatric Conditions": 2.9,
      "Cancer": 6.9,
      "Number of older adults": 2105,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Jammu & Kashmir",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 34.1,
      "Heart Disease": 11.5,
      "Stroke": 2.9,
      "Diabetes Mellitus": 12.3,
      "Neurological/Psychiatric Conditions": 3.3,
      "Cancer": 3.1,
      "Number of older adults": 1603,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Himachal Pradesh",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 21.3,
      "Heart Disease": 10.2,
      "Stroke": 4.4,
      "Diabetes Mellitus": 14,
      "Neurological/Psychiatric Conditions": 7.6,
      "Cancer": 5.6,
      "Number of older adults": 1380,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Haryana",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 25.6,
      "Heart Disease": 7.1,
      "Stroke": 1.4,
      "Diabetes Mellitus": 13.8,
      "Neurological/Psychiatric Conditions": 2.8,
      "Cancer": 3.8,
      "Number of older adults": 1893,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Delhi",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 19.3,
      "Heart Disease": 9.2,
      "Stroke": 1.7,
      "Diabetes Mellitus": 18.3,
      "Neurological/Psychiatric Conditions": 3.2,
      "Cancer": 2,
      "Number of older adults": 1315,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    },
    {
      "srcStateName": "Chandigarh",
      "Region": "North",
      "srcYear": "2022-23",
      "Age Group": "Greater than 45",
      "Hypertension": 39.2,
      "Heart Disease": 13.5,
      "Stroke": 4.2,
      "Diabetes Mellitus": 30.3,
      "Neurological/Psychiatric Conditions": 7.8,
      "Cancer": 7.5,
      "Number of older adults": 1003,
      "Additional Info": "*: Including spouse irrespective of age",
      "YearCode": 2022,
      "Year": "Financial Year (Apr - Mar), 2022"
    }
  ]
  // Extracting health conditions
  const healthConditions = [
    "Hypertension",
    "Heart Disease",
    "Stroke",
    "Diabetes Mellitus",
    "Neurological/Psychiatric Conditions",
    "Cancer"
  ];

  // Prepare data for line chart
  const lineChartData = healthConditions.map(condition => ({
    name: condition,
    data: data.map(item => ({
      x: item.srcStateName,
      y: item[condition]
    }))
  }));

  // Chart options
  const options = {
    chart: {
      height: 400,
      type: 'line',
      toolbar: {
        show: true,
        tools: {
          download: true,
          selection: true,
          zoom: true,
          zoomin: true,
          zoomout: true,
          pan: true,
          reset: true
        }
      }
    },
    title: {
      text: 'Prevalence of Health Conditions Among Older Adults in Southern India (Financial Year 2022-23)'
    },
    xaxis: {
      type: 'category',
      categories: data.map(item => item.srcStateName),
      title: {
        text: 'State'
      }
    },
    yaxis: {
      title: {
        text: 'Prevalence (%)'
      }
    },
    legend: {
      show: true
    }
  };

  return (
    <div className="col-span-12 rounded-sm border border-stroke bg-white px-5 pt-7.5 pb-5 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 ">
      <Chart options={options} series={lineChartData} type="line" height={400} />
    </div>
  );
};

export default LineChart;
